import "./globals.css";

import type { Metadata } from "next";
import { DM_Sans,Playfair_Display } from "next/font/google";

import { Providers } from "@/shared/providers/query";

const playfair = Playfair_Display({
    variable: "--font-playfair",
    subsets: ["latin"],
    display: "swap",
});

const dmSans = DM_Sans({
    variable: "--font-dm-sans",
    subsets: ["latin"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "E-commerce",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="overflow-x-hidden">
            <body className={`${dmSans.variable} ${playfair.variable} antialiased overflow-x-hidden`}>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
